### ISSUE TITLE
[ref] k8s

### ISSUE THREAD

**Issue by at15** [benchhub/benchhub#3]
Actually CI #2 is pretty similar to k8s in some sense, a master a control job dispatch, a worker to run the job, except in k8s the job can be a long running application instead of some test

- [ ] how is the node agent `kublet` keep heart beat with master (or `etcd`?)
- [ ] kube-proxy, istio, envoy etc. .... where is the proxy exactly @gaocegege said I should google for myself /w\
- [ ] it might be easier to understand everything by setting up a k8s following https://github.com/kelseyhightower/kubernetes-the-hard-way
- [ ] k8s scheduler, so for BenchHub, or scheduler is much simpler, every job is short time, and we don't want to have parallel job execution due to interference, i.e. MySQL and PgSQL on same machine and compete for both CPU and IO
  - [ ] it seems to be a two level scheduler like Mesos
- [x] [浅入了解容器编排框架调度器之 Kubernetes](https://zhuanlan.zhihu.com/p/29691157) by @gaocegege (狗粮哥哥)
- [x] https://engineering.bitnami.com/articles/a-deep-dive-into-kubernetes-controllers.html
- [x] https://blog.heptio.com/core-kubernetes-jazz-improv-over-orchestration-a7903ea92ca
- [x] https://dzone.com/articles/kubernetes-lifecycle-of-a-pod
- [x] [kubernetes设计理念分析 | 从运行流程和list-watch看kubernetes系统的设计理念](https://mp.weixin.qq.com/s?__biz=MzUzNzYxNjAzMg==&mid=2247483683&idx=1&sn=0a92e0e8e0d54d6ee76852f9db45b181&pass_ticket=HZPrXHGPCWrYW4HMZTV9MZ19kAGoK72zI%2FlkaARMhlOZLmeOGGuGDjrhWBOGbSj2)

**Comment by at15** [comment]
might checkout swarm as well ~~https://github.com/docker/swarmkit~~ swarmkit is not swarm https://github.com/docker/swarm ... though it seems it's not in a active state ... and https://github.com/docker/libcompose seems to be dead as well

**Comment by gaocegege** [comment]
swarm 就别看了, 已经一首凉凉送给他
