### ISSUE TITLE
[scheduler] Rethink interface for scheduler

### ISSUE THREAD

**Issue by at15** [benchhub/benchhub#49]
Was looking at k8s' scheduler interface, it seems it picks one pod and several nodes, filters nodes, picks the best one and call it a day, however, it may not fit benchhub well

- schedule node one by one may not be global optimal, i.e. I have one node any and one node loader, the loader pick the any node, and the db node got no node to pick ...

stuff suggested by @gaocegege

- https://github.com/kubernetes-incubator/kube-arbitrator batch job sceduling
- node affinity https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#node-affinity-beta-feature

> nodeSelector continues to work as usual, but will eventually be deprecated, as node affinity can express everything that nodeSelector can express.

It's pretty similar to our rule that a node running database can no longer run database

> Inter-pod affinity and anti-affinity were introduced in Kubernetes 1.4. Inter-pod affinity and anti-affinity allow you to constrain which nodes your pod is eligible to be scheduled based on labels on pods that are already running on the node rather than based on labels on nodes.

Ref

- https://ucbrise.github.io/cs294-rise-fa16/cluster_management.html
- https://ucbrise.github.io/cs294-rise-fa16/realtime_systems.html
  - Low latency schgeduling of dependent tasks

**Comment by gaocegege** [comment]
I think node affinity is better since there is no dev work to do.

**Comment by at15** [comment]
@gaocegege I am not using k8s now .... but in the future, benchhub should be able to run inside other scheduler, currently I just want to reinvent the wheel /w\
